apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself

metadata:
  name: stack-mars

spec:
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true

        title:
          title: Titulo
          type: string
          description: Unique name of the component
        
        description:
          title: Descrição
          type: string
          description: Unique name of the component
          ui:options:
            rows: 5


    