apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself

metadata:
  name: stack-mars

spec:
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:

        testp:
          properties:
            dynamodb:
              title: dynamo
              type: string
              description: teste
            
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true

        title:
          title: Titulo
          type: string
          description: Unique name of the component
        
        description:
          title: Descrição
          type: string
          description: Unique name of the component
          ui:options:
            rows: 5

  steps:
      - id: fetch-base
        name: Fetch Base
        action: fetch:template
        input:
          url: ./template
          values:
            name: '{{ parameters.name }}'

      - id: fetch-docs
        name: Fetch Docs
        action: fetch:plain
        input:
          targetPath: ./community
          url: https://github.com/backstage/community/tree/main/backstage-community-sessions

      - id: publish
        name: Publish
        action: publish:github
        input:
          allowedHosts: ['github.com']
          description: 'This is {{ parameters.name }}'
          repoUrl: '{{ parameters.repoUrl }}'

      - id: register
        name: Register
        action: catalog:register
        input:
          repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
          catalogInfoPath: '/catalog-info.yaml'